version: "2"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:4.1.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
    - 2181:2181
    logging: { driver: none }

  broker:
    image: confluentinc/cp-kafka:4.1.0
    ports:
    - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: plaintext://broker:9092
      KAFKA_NUM_PARTITIONS: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 10
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_JMX_HOSTNAME: broker
      KAFKA_JMX_PORT: 9010
    depends_on: [zookeeper]

  jmx_exporter:
    build:
      context: .
      args:
        version: 0.3.1
    ports:
    - 9209:9209
    environment:
      EXPORTER_CONF: /jmx_exporter.yml
    volumes:
    - ./jmx_exporter.yml:/jmx_exporter.yml
