version: "2"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:4.1.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
    - 2181:2181
    logging: { driver: none }

  broker:
    image: confluentinc/cp-kafka:4.1.0
    ports:
    - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: plaintext://broker:9092
      KAFKA_NUM_PARTITIONS: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 10
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_JMX_HOSTNAME: broker
      KAFKA_JMX_PORT: 9010
    depends_on: [zookeeper]

    #  connect:
    #    image: confluentinc/cp-kafka-connect:4.1.0
    #    ports:
    #    - 8083:8083
    #    environment:
    #      CONNECT_BOOTSTRAP_SERVERS: broker:9092
    #      CONNECT_ZOOKEEPER_CONNECT: zookeeper:2181
    #      CONNECT_REST_ADVERTISED_HOST_NAME: connect
    #      CONNECT_REST_PORT: 8083
    #      CONNECT_GROUP_ID: connect-cluster
    #      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
    #      CONNECT_CONFIG_STORAGE_PARTITIONS: 1
    #      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
    #      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
    #      CONNECT_OFFSET_STORAGE_PARTITIONS: 10
    #      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
    #      CONNECT_STATUS_STORAGE_TOPIC: connect-status
    #      CONNECT_STATUS_STORAGE_PARTITIONS: 5
    #      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
    #      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
    #      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
    #      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
    #      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
    #      CONNECT_PLUGIN_PATH: /usr/share/java
    #      KAFKA_JMX_HOSTNAME: connect
    #      KAFKA_JMX_PORT: 9010
    #    depends_on: [zookeeper, broker]

    #  rest-proxy:
    #    image: confluentinc/cp-kafka-rest:4.1.0
    #    ports:
    #    - 8082:8082
    #    environment:
    #      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
    #      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
    #      KAFKA_REST_HOST_NAME: "rest-proxy"
    #      KAFKA_REST_JMX_HOSTNAME: rest-proxy
    #      KAFKA_REST_JMX_PORT: 9010
    #    depends_on: [zookeeper, broker]

  jmx_exporter:
    build:
      context: .
      args:
        version: 0.3.1
    ports:
    - 9209:9209
    environment:
      EXPORTER_CONF: /jmx_exporter.yml
    volumes:
      - ./jmx_exporter.yml:/jmx_exporter.yml
